SELECT 'test';

INSERT INTO USER(ID, NAME, PASSWORD, LOGIN, ROLE)
VALUES (0, 'string', '$2a$04$eax4hv/iPeNneBtky.G8reAWCI2r6r07z6yEn6BTV2r.9OufLrxRS', 'string', 'ROLE_STUDENT');
INSERT INTO USER(ID, NAME, PASSWORD, LOGIN, ROLE)
VALUES (1, 'lector', '$2a$04$eax4hv/iPeNneBtky.G8reAWCI2r6r07z6yEn6BTV2r.9OufLrxRS', 'lector', 'ROLE_LECTOR');


INSERT INTO COURSE (ID, YEAR, FACULTY)
VALUES (1, 2017, 'FI');
INSERT INTO COURSE (ID, YEAR, FACULTY)
VALUES (2, 2018, 'FEN');
INSERT INTO COURSE (ID, YEAR, FACULTY)
VALUES (3, 2019, 'FGN');
INSERT INTO COURSE (ID, YEAR, FACULTY)
VALUES (4, 2020, 'FPRN');
INSERT INTO COURSE (ID, YEAR, FACULTY)
VALUES (5, 2021, 'FSNST');

INSERT INTO LECTOR(CATHEDRA, ID)
VALUES ('Multimedia', 1);

INSERT INTO SLOT (ID, DAY, ROOM, TIME, COURSE_ID, LECTOR_ID)
VALUES (1, 'MONDAY', '228-room', 'FIRST', 1, 1);
INSERT INTO SLOT (ID, DAY, ROOM, TIME, COURSE_ID, LECTOR_ID)
VALUES (2, 'TUESDAY', '228-room', 'SECOND', 2, 1);
INSERT INTO SLOT (ID, DAY, ROOM, TIME, COURSE_ID, LECTOR_ID)
VALUES (3, 'WEDNESDAY', '228-room', 'THIRD', 3, 1);
INSERT INTO SLOT (ID, DAY, ROOM, TIME, COURSE_ID, LECTOR_ID)
VALUES (4, 'THURSDAY', '228-room', 'FOURTH', 4, 1);
INSERT INTO SLOT (ID, DAY, ROOM, TIME, COURSE_ID, LECTOR_ID)
VALUES (5, 'FRIDAY', '228-room', 'FIFTH', 5, 1);
